### ISSUE TITLE
composer package 不会自动更新 

### ISSUE THREAD

**Issue by phpdever** [MobClub/mobpush-websdkv3-php#3]
通过查看 Commits ：fix target rids bug，确实修复了一个通过 Reg id推送会使用别名推送的Bug。

![image](https://user-images.githubusercontent.com/17875582/90208586-bdeb0200-de1b-11ea-85e6-fa195975b131.png)

但在 composer package (https://packagist.org/packages/mob/mobpush) 

这个扩展似乎不会自动更新。

![image](https://user-images.githubusercontent.com/17875582/90208634-dbb86700-de1b-11ea-9439-3638536e1214.png)

这将直接导致我通过：composer require mob/mobpush -vvv 命令 引入依赖不会是最新的。

这个问题很严重！

**Comment by Larry1992Fei** [comment]
感谢您的反馈， 已配置为自动更新了
